# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 【TeacherOS 專案記憶 — Layer 2】
# 名稱：七年級 A 班（英文科任）
# 路徑：projects/class-7a/project.yaml
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class: 7A
grade: 七年級
teacher_role: 英文科任教師
di_framework_ref: projects/_di-framework/project.yaml

subjects_taught:
  english:
    type: 英文專科
    weekly_sessions: 4

current_semester: 2025-2026

# ── 班級狀態 ──────────────────────────────────────────────────
status: dormant
# dormant 意義：結構就緒，但尚未啟動任何工作線。AI 載入系統時不主動讀取此班級。
#
# 啟動條件（滿足任一即可啟動）：
#   - David 說「我要開始 7A 英文課」
#   - David 說「新增一個班級科目」
#   - David 明確指示開始 7A 的任何工作
#
# 啟動後 AI 應執行：
#   1. 將 status 改為 active
#   2. 提示教師填入 students.yaml（DI 樣態）
#   3. 開始 Block 1（英文學季大綱設計）

current_focus: 休眠中（尚未啟動）
next_steps:
  - 啟動時：填入 7A 學生 DI 樣態（students.yaml）
  - 啟動時：開始 Block 1 — 7A 英文學季大綱設計（可直接複用 9C 英文 Block 1 模板）
