# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 【TeacherOS 專案記憶 — Layer 2】
# 名稱：九年級 C 班（David 導師班・英文・主課程）
# 路徑：projects/class-9c/project.yaml
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class: 9C
grade: 九年級
teacher_role: 導師（班導師）
di_framework_ref: projects/_di-framework/project.yaml

homeroom_context: >
  David 為 9C 導師，與學生關係最深。
  同時承擔主課程與英文課，對班級整體發展有完整的觀察與責任。

# ── 班級檔案索引（AI 讀這裡就知道要載入什麼）────────────────
class_files:
  roster: roster.yaml              # gitignored，學生身份（真名+ID+座號）
  students: students.yaml          # 班級共用 DI 摘要 + 跨科特殊狀況
  session_state: working/english-session.yaml  # 英文課工作進度錨點
  homeroom_session: homeroom/session.yaml      # 導師專用進度錨點

subjects:
  homeroom:
    type: 班級導師模組
    note: 負責班級經營、活動行事與親師溝通
    session_anchor: homeroom/session.yaml
    calendar_ref: homeroom/reference/calendar.md
    content_output: homeroom/content/
  english:
    type: 英文專科
    weekly_sessions: 4
    lesson: english/lesson.yaml
    di_profile: english/di-profile.yaml
    assessment: english/assessment.yaml
    content_output: english/content/
  main_lesson:
    type: 主課程
    note: David 為 9C 主課程教師，課程主題待本學期確認
    lesson: main-lesson/lesson.yaml
    di_profile: main-lesson/di-profile.yaml
    assessment: main-lesson/assessment.yaml

current_semester: 2025-2026
current_focus: 英文 Block 2（第 1–2 週課堂設計）；導師 Block 3（春季班親會準備）

next_steps:
  - 英文：Block 2 — 設計第 1–2 週 45 分鐘課堂流程（小說研讀 + 語言工坊）
  - 導師：Block 3 — 確認春季班親會細節（2026-03-21）
  - 主課程：建立 main-lesson-di-template.md 後啟動 Block 1

# ── 班內橫向連結備忘（AI 開工前可快速掃描）──────────────────
# 用途：記錄英文、主課程、導師三個工作線之間的協調事項
# 維護：AI 在任何科目工作時，若發現跨線影響，主動寫入此區塊
# 格式：- "[日期] [科目A]→[科目B] 說明"
cross_module_notes:
  active:
    - "2026-03-01 導師→英文 春季班親會 2026-03-21 在第 3 週，規劃課堂進度時留意該週節奏可能調整"
  resolved: []
  # 說明：
  #   active  — 目前仍需要跨線注意的事項
  #   resolved — 已解決或已過期，定期清理
